### ISSUE TITLE
Error in split_data.py

### ISSUE THREAD

**Issue by nitishgupta** [TellinaTool/nl2bash#11]
When I'm trying to preprocess the training data, I get an error in the split_data.py script.
```
Traceback (most recent call last):
  File "scripts/split_data.py", line 158, in <module>
    split_data(data_dir)
  File "scripts/split_data.py", line 50, in split_data
    nl_temp = get_nl_temp(nl)
  File "scripts/split_data.py", line 27, in get_nl_temp
    return ' '.join(basic_tokenizer(nl)[0])
  File "../nlp_tools/tokenizer.py", line 125, in basic_tokenizer
    word = spc.correction(word)
  File "../nlp_tools/spellcheck/spell_check.py", line 45, in correction
    return max(candidates(word), key=P)
  File "../nlp_tools/spellcheck/spell_check.py", line 41, in P
    return WORDS[word] / (N+0.0)
ZeroDivisionError: float division by zero
```

What can I do to tokenize and split the data correctly?

**Comment by todpole3** [comment]
Did you run `make` in the repo root?

This will untar the file `nlp_tools/spellcheck/most_common.tar.xz` to `nlp_tools/spellcheck/most_common.txt`, which is read by the spell checker.

**Comment by nitishgupta** [comment]
Thanks, I figured it out. I didn't understand that the readme meant to run `make` in the repo-root directory.
