### ISSUE TITLE
Source code of master branch is broken

### ISSUE THREAD

**Issue by kambehmw** [TellinaTool/nl2bash#23]
Which is the commit version of the stable code?
`make data` command of the current master branch cannot be executed normally.

**Comment by grwlf** [comment]
+1

I see the following errors:

1.
```
Reading data from /workspace/3rdparty/nl2bash/encoder_decoder/data
Saving models to /workspace/3rdparty/nl2bash/encoder_decoder/../model/seq2seq
Preparing data in /workspace/3rdparty/nl2bash/encoder_decoder/data
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/3rdparty/nl2bash/encoder_decoder/translate.py", line 378, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/workspace/3rdparty/nl2bash/encoder_decoder/translate.py", line 293, in main
    process_data()
  File "/workspace/3rdparty/nl2bash/encoder_decoder/translate.py", line 252, in process_data
    data_utils.process_data(FLAGS)
AttributeError: module 'data_processor.data_utils' has no attribute 'process_data'
Makefile:10: recipe for target 'data' failed

```

I found process_data in another module, called `data_processor.py`. But if I call it  I get another error:


2.
```
train - 7340 pairs, dev - 549 pairs, test - 547 pairs                                                                     
# Convert raw parallel corpus to features taken by the neural network
./bash-run.sh --process_data --dataset bash                                                      
Bashlint grammar set up (124 utilities)                                                          
                        
Reading data from /workspace/3rdparty/nl2bash/encoder_decoder/data                                                        
Saving models to /workspace/3rdparty/nl2bash/encoder_decoder/../model/seq2seq
Preparing data in /workspace/3rdparty/nl2bash/encoder_decoder/data                                                        
Split - train                                                                                    
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main                  
    "__main__", mod_spec) 
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code                                      
    exec(code, run_globals)                                  
  File "/workspace/3rdparty/nl2bash/encoder_decoder/translate.py", line 379, in <module>
    tf.compat.v1.app.run()                                                                       
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)           
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run                                             
    _run_main(main, args)                                                                        
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main                                       
    sys.exit(main(argv))                                                                         
  File "/workspace/3rdparty/nl2bash/encoder_decoder/translate.py", line 294, in main                                      
    process_data()                                                                               
  File "/workspace/3rdparty/nl2bash/encoder_decoder/translate.py", line 253, in process_data
    data_processor.process_data(FLAGS)                                                           
  File "/workspace/3rdparty/nl2bash/data_processor/data_processor.py", line 29, in process_data                           
    process_dataset_split(data_dir, 'train', channel=channel)
  File "/workspace/3rdparty/nl2bash/data_processor/data_processor.py", line 49, in process_dataset_split
    nl_list, cm_list = read_parallel_data(nl_path, cm_path)                                                               
  File "/workspace/3rdparty/nl2bash/data_processor/data_processor.py", line 40, in read_parallel_data
    with open(nl_path) as f:                                                                     
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/3rdparty/nl2bash/encoder_decoder/data/train.nl.filtered'

```

**Comment by grwlf** [comment]
Above errors were seen at `6663ca13e`.

**Comment by grwlf** [comment]
It seems that Nl2bash master branch is in the process of trainsition to JSON data format, but it doesn't work yet. In my project I've managed to combine old and new code into a monster, able to produce the data in _old_ data format (the one with many files). No models are attached to it yet.

https://github.com/stagedml/stagedml/tree/master/3rdparty/nl2bash_essence

**Comment by todpole3** [comment]
Master branch rebased to stable commit. 

@grwlf is right. We are in the process of transition into JSON data format but haven't quite finished yet. The changes can be seen in the `development` branch. Previously the two branches got messed up. Sorry about this issue.

**Comment by cjy-cc** [comment]
您好先生，我想向您请教一个问题，您是如何解决这个问题的？谢谢您了。

**Comment by cjy-cc** [comment]
Hello Sir, I would like to ask you a question. How did you solve this problem?Thank you very much.

**Comment by mernst** [comment]
The [comment](https://github.com/TellinaTool/nl2bash/issues/23#issuecomment-587207762) says how.
