### ISSUE TITLE
An error in the part of make train

### ISSUE THREAD

**Issue by NingYueran** [TellinaTool/nl2bash#35]
Dear professor:
I'm sorry to disturb you, I met a problem in make train, the problem is as follows:
Traceback (most recent call last):
File "/home/admin318/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/admin318/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/admin318/nl2bash-master/encoder_decoder/translate.py", line 378, in
tf.compat.v1.app.run()
File "/home/admin318/anaconda3/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
_run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
File "/home/admin318/anaconda3/lib/python3.8/site-packages/absl/app.py", line 312, in run
_run_main(main, args)
File "/home/admin318/anaconda3/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
sys.exit(main(argv))
File "/home/admin318/nl2bash-master/encoder_decoder/translate.py", line 320, in main
train_set, dev_set, test_set = data_utils.load_data(FLAGS, use_buckets=True)
File "/home/admin318/nl2bash-master/encoder_decoder/data_utils.py", line 136, in load_data
train_set = read_data(FLAGS, 'train', source, target, load_features=load_features,
File "/home/admin318/nl2bash-master/encoder_decoder/data_utils.py", line 250, in read_data
compute_copy_indices(sc_tokens, tg_tokens,
File "/home/admin318/nl2bash-master/encoder_decoder/data_utils.py", line 738, in compute_copy_indices
assert(len(sc_tokens) == len(sc_copy_tokens))
AssertionError
Makefile:42: recipe for target 'train' failed
I'm looking forward to your reply

**Comment by NingYueran** [comment]
Dear professor: 
I'm sorry to disturb you, I met a problem in make train, the problem is as follows:
Traceback (most recent call last):
  File "/home/admin318/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/admin318/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/admin318/nl2bash-master/encoder_decoder/translate.py", line 378, in <module>
    tf.compat.v1.app.run()
  File "/home/admin318/anaconda3/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/admin318/anaconda3/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/admin318/anaconda3/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/admin318/nl2bash-master/encoder_decoder/translate.py", line 320, in main
    train_set, dev_set, test_set = data_utils.load_data(FLAGS, use_buckets=True)
  File "/home/admin318/nl2bash-master/encoder_decoder/data_utils.py", line 136, in load_data
    train_set = read_data(FLAGS, 'train', source, target, load_features=load_features,
  File "/home/admin318/nl2bash-master/encoder_decoder/data_utils.py", line 250, in read_data
    compute_copy_indices(sc_tokens, tg_tokens,
  File "/home/admin318/nl2bash-master/encoder_decoder/data_utils.py", line 738, in compute_copy_indices
    assert(len(sc_tokens) == len(sc_copy_tokens))
AssertionError
Makefile:42: recipe for target 'train' failed
I'm looking forward to your reply
